### ISSUE TITLE
dxfgrabber does not support DXF files with only an ENTITIES section

### ISSUE THREAD

**Issue by LHolst** [mozman/dxfgrabber#3]
hi mozman, im trying to read an example dxf file from Stuttgart, Germany 3D Citymodel page http://www.stuttgart.de/item/show/492022  
the files are in an archive at https://gis6.stuttgart.de/data/testdaten/DXF/Geb%C3%A4udemodell.zip

when opening it with dxfgrabber no entities are reported, same with the blender-dxf-import plugin where dxfgrabber is used to open dxf files.

after searching around i found ezdxf, and tried to open the `LOD2_Geometrien.dxf` and saved it as a new dxf file in hope of upgrading the dxf version of the file. unfortunately, that results in an error while importing with blender
``` python
Traceback (most recent call last):
  File "/usr/share/blender/2.78/scripts/addons/io_import_dxf/__init__.py", line 540, in execute
    proj_dxf, proj_scn, self.represent_thickness_and_width, self.import_atts, dxf_unit_scale)
  File "/usr/share/blender/2.78/scripts/addons/io_import_dxf/__init__.py", line 119, in read
    errors = do.entities(os.path.basename(filename).replace(".dxf", ""), new_scene)
  File "/usr/share/blender/2.78/scripts/addons/io_import_dxf/dxfimport/do.py", line 1611, in entities
    self.combined_objects((en for en in self.dwg.modelspace() if is_.combined_entity(en)), scene)
  File "/usr/share/blender/2.78/scripts/addons/io_import_dxf/dxfimport/do.py", line 1515, in combined_objects
    o = self._call_object_types(TYPE, by_att, group, name, scene, False)
  File "/usr/share/blender/2.78/scripts/addons/io_import_dxf/dxfimport/do.py", line 1364, in _call_object_types
    o = type_func(entity, scene, name)
  File "/usr/share/blender/2.78/scripts/addons/io_import_dxf/dxfimport/do.py", line 1236, in object_mesh
    self.the3dface(en, bm)
  File "/usr/share/blender/2.78/scripts/addons/io_import_dxf/dxfimport/do.py", line 526, in the3dface
    self._gen_meshface(points, bm)
  File "/usr/share/blender/2.78/scripts/addons/io_import_dxf/dxfimport/do.py", line 512, in _gen_meshface
    bm.faces.remove(face)
ReferenceError: BMesh data of type BMFace has been removed

location: <unknown location>:-1

```

but fortunately, after doing that convertion with ezdxf, dxfgrabber now reports  11296 `3DFACE`'s  
is this dataset outdated in form of dxf version ? would it be a good idea to first upgrade the dxf file with ezdxf before handling the content dxfgrabber?

**Comment by mozman** [comment]
Hi!

LOD1_Geometrien.dxf: AutoCAD Trueview count 7851 objects

LOD2_Geometrien.dxf: AutoCAD Trueview count 11296 objects

This is the simplest form of 3D data DXF supports, every face is a single DXF object. May be a mesh processor like MeshLab can help t create a Polyface object.

The DXF files have just an ENTITIES section, dxfgrabber does not support this kind of DXF files now, I will add this feature in the next version.

Best regards,
Manfred

**Comment by LHolst** [comment]
Wow thanks for your lightning fast response, that are good news.

**Comment by mozman** [comment]
dxfgrabber v0.8.4 can read DXF files with only an ENTITIES section
