### ISSUE TITLE
Better Error for Wrong File Type

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [mozman/dxfgrabber#4]
The file [saber1_0.dxf.zip](https://github.com/mozman/dxfgrabber/files/892760/saber1_0.dxf.zip) is actually an AC1003 type file which I think is a DWG not a DXF. The below error that I get when reading the file doesn't indicate that is actually the problem. Is it possible for a better error to be raised indicating an improper file type?

```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dxfgrabber
>>> dxfgrabber.readfile('saber1_0.dxf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dxfgrabber/__init__.py", line 43, in readfile
    return readfile_as_asc(filename, options)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dxfgrabber/__init__.py", line 58, in readfile_as_asc
    return _read_encoded_file(filename, options, encoding=get_encoding())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dxfgrabber/__init__.py", line 65, in _read_encoded_file
    dwg = Drawing(fp, options)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dxfgrabber/drawing.py", line 30, in __init__
    sections = Sections(tagreader, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dxfgrabber/sections.py", line 21, in __init__
    self._setup_sections(tagreader, drawing)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dxfgrabber/sections.py", line 37, in _setup_sections
    for section in iterchunks(tagreader, stoptag='EOF', endofchunk='ENDSEC'):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dxfgrabber/defaultchunk.py", line 35, in iterchunks
    tag = next(tagreader)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dxfgrabber/tags.py", line 158, in stream_tagger
    raise DXFStructureError("Missing required y coordinate near line: {}.".format(line.counter))
dxfgrabber.tags.DXFStructureError: Missing required y coordinate near line: 54.
```

$ pip3 show dxfgrabber
Name: dxfgrabber
Version: 0.8.1

**Comment by mozman** [comment]
Hi!

This is a DXF created by an application,  which writes LINE coordinates as x1, x2, y1, y2 which is not supported by dxfgrabber. I think qcad had this issue, but they changed the DXF export to x1, y1, x2, y2.

This DXF file will never work with dxfgrabber or ezdxf. And the error message says exactly what happens,
dxfgrabber expected a y-coordinate and got a x-coordinate.

Best regards,
Manfred

**Comment by BebeSparkelSparkel** [comment]
I think that you are correct in stating that there is an x y mixup. It also seems that the x y mixup is not the only problem with the [saber1_0.dxf.zip](https://github.com/mozman/dxfgrabber/files/892760/saber1_0.dxf.zip) file; it is also too old for dxfgrabber to read.

From previous correspondence we determined that AC1003 is too old to read.

> DXF version is AC1003, much older than AC1009 (DXF R12), dxfgrabber is not tested with DXF version older than DXF12.
> 
> If i have time i will look at the problem, but there are no DXF specification for that old DXF versions.
> 
> Best regards

The error encountered for the old file type was also unclear about the problem when used on [Design51.dxf.zip](https://github.com/mozman/dxfgrabber/files/896011/Design51.dxf.zip)
```
>>> import dxfgrabber
>>> dxfgrabber.readfile("Design51.dxf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/__init__.py", line 43, in readfile
    return readfile_as_asc(filename, options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/__init__.py", line 58, in readfile_as_asc
    return _read_encoded_file(filename, options, encoding=get_encoding())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/__init__.py", line 65, in _read_encoded_file
    dwg = Drawing(fp, options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/drawing.py", line 30, in __init__
    sections = Sections(tagreader, self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/sections.py", line 21, in __init__
    self._setup_sections(tagreader, drawing)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/sections.py", line 48, in _setup_sections
    new_section = section_class.from_tags(section, drawing)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/tablessection.py", line 59, in from_tags
    tables_section._setup_tables(tags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/tablessection.py", line 74, in _setup_tables
    new_table = table_class.from_tags(table, self._drawing)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/linetypes.py", line 30, in from_tags
    styles._table_entries[dxfstyle.get_dxf_attrib('name')] = Linetype(dxfstyle)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/linetypes.py", line 15, in __init__
    self.name = wrapper.get_dxf_attrib('name')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/dxfentity.py", line 49, in get_dxf_attrib
    return self._get_dxf_attrib(dxfattr)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dxfgrabber/dxfentity.py", line 58, in _get_dxf_attrib
    subclass_tags = self.tags.subclasses[dxfattr.subclass]
IndexError: list index out of range
```

It is very hard to try and catch various errors (dxfgrabber.tags.DXFStructureError and IndexError to name two) that dxfgrabber raises when it encounters an incompatible file type that isn't:
AC1009
AC1015
AC1018
AC1021
AC1024
AC1027

**Comment by mozman** [comment]
May be you work with an old version of dxfgrabber, dxfgrabber v0.8.4 opens Design51.dxf without errors.

**Comment by BebeSparkelSparkel** [comment]
Do you know if v0.8.4 is backwards compatible with v0.8.1? When I upgraded to v0.8.1 I had problems with method names being changed slightly from my previous version and it took a while to sort that out.

**Comment by mozman** [comment]
No renaming since v0.8.0
